# Generated by Django 3.1.5 on 2021-04-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0002_auto_20210420_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffschedule',
            name='staff_type',
            field=models.CharField(default='Caretaker', max_length=100),
        ),
    ]
