# Generated by Django 3.1.5 on 2021-05-04 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0005_auto_20210422_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=4)),
                ('block_no', models.CharField(max_length=1)),
                ('room_cap', models.IntegerField(default=3)),
                ('room_occupied', models.IntegerField(default=0)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_management.hall')),
            ],
        ),
    ]
