# Generated by Django 3.1.5 on 2021-05-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0007_workerreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkerReport',
        ),
    ]
