# Generated by Django 3.1.5 on 2021-05-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_module', '0002_auto_20200522_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel_allotment',
            name='year',
            field=models.IntegerField(default=2016),
        ),
    ]
